### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by Vaibhav-21-git** [prashanth-up/Meet-Automation#3]
See i have my account and my school account. we have to use school account to join the meet so what should i do?

**Comment by moiSentineL** [comment]
only thing you can do now, is to sign out from your personal account so that it recognises your school account for G Meet. Kudos.

**Comment by Vaibhav-21-git** [comment]
> only thing you can do now, is to sign out from your personal account so that it recognises your school account for G Meet. Kudos.

So is it possible to do like use different user for different account?

**Comment by prashanth-up** [comment]
Yes, you can set the default browser gmail to the school one. This automation is for the default browser signed in mail only.
